### ISSUE TITLE
NullPointerException in checkMethodCall

### ISSUE THREAD

**Issue by mingc-vnera** [mbechler/serianalyzer#1]
I got this error when I run serianalyzer 
Found 6963 serializable classes
Exception in thread "main" java.lang.NullPointerException
	at serianalyzer.Serianalyzer.checkMethodCall(Serianalyzer.java:1041)
	at serianalyzer.SerianalyzerMethodVisitor.visitMethodInsn(SerianalyzerMethodVisitor.java:515)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at serianalyzer.Serianalyzer.checkClass(Serianalyzer.java:921)
	at serianalyzer.Serianalyzer.checkClass(Serianalyzer.java:928)
	at serianalyzer.Serianalyzer.runAnalysis(Serianalyzer.java:245)
	at serianalyzer.Serianalyzer.restoreOrRunAnalysis(Serianalyzer.java:120)
	at serianalyzer.Serianalyzer.analyze(Serianalyzer.java:95)
	at serianalyzer.Main.main(Main.java:83)

**Comment by mbechler** [comment]
The NPE should be fixed. However I guess this is trigged by not adding a java runtime (at least rt.jar or the whole jre lib/ directory) to the analyzed classpath. You should do that, otherwise I wouldn't expect useful results.

**Comment by mingc-vnera** [comment]
Thanks. That make sense.
